#!/usr/bin/env python3
"""
make_report_text.py — assemble results/final/FINAL_RESULTS.md from the saved
CSVs. Every number is read from disk; none is typed by hand.
"""

from __future__ import annotations

import os
import sys

import numpy as np
import pandas as pd
import yaml

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
PROJECT_DIR = os.path.abspath(os.path.join(HERE, ".."))


def main():
    with open(os.path.join(HERE, "final.yaml")) as f:
        cfg = yaml.safe_load(f)
    out = os.path.join(PROJECT_DIR, cfg["output_dir"], "final")
    ds = [d["name"] for d in cfg["datasets"]]
    prim = pd.read_csv(os.path.join(out, "table_primary.csv"))
    abl = pd.read_csv(os.path.join(out, "table_ablation.csv"))
    det = pd.read_csv(os.path.join(out, "table_detectors.csv"))
    stats = pd.read_csv(os.path.join(out, "stats.csv"))
    cost = pd.read_csv(os.path.join(out, "cost_savings.csv"))
    dstats = pd.read_csv(os.path.join(out, "dataset_stats.csv"))
    leak = pd.read_csv(os.path.join(out, "leakage_check.csv"))
    refit = pd.read_csv(os.path.join(out, "refit_timing.csv"))
    env = pd.read_json(os.path.join(out, "env.json"), typ="series")

    def g(n, m, c):
        r = prim[(prim.dataset == n) & (prim.model == m)]
        return float(r[c].iloc[0]) if len(r) else float("nan")

    L = ["# Final results (single run)\n",
         f"Generated by `final/make_report_text.py` from `results/paper_final_run/final/*.csv`. "
         f"Config `final/final.yaml`; seeds {cfg['seeds']}; "
         f"initial-train fraction {cfg['initial_train_fraction']} "
         f"({cfg['prefix_rounding']}); per-dataset window sizes "
         + ", ".join(f"{d['name']}={d['window_rows']}" for d in cfg["datasets"]) + ".\n"]

    L.append("## Environment\n")
    for k in ["python", "platform", "cpu_count", "timestamp"]:
        if k in env.index:
            L.append(f"- {k}: `{env[k]}`")
    L.append("## No-leakage verification\n")
    if "max_train_window" in leak.columns:
        L.append(f"- windows scored: {len(leak)}; any evaluation whose training "
                 f"buffer contained a window with index >= the scored window: "
                 f"{int(leak['future_buffer'].sum())}; "
                 f"max(max_train_buffer_window - scored_window) "
                 f"= {int((leak['max_train_window']-leak['window_idx']).max())}\n")
    else:
        L.append(f"- windows scored: {len(leak)}. The in-loop guard asserts "
                 f"`max_train_window < window_idx` before every prediction, so a "
                 f"leak would have raised; no violation occurred.\n")

    L.append("## Datasets\n")
    L.append("| Dataset | Samples | Features | Windows | Regimes | Transitions | Recurrences |")
    L.append("|---|---|---|---|---|---|---|")
    for _, r in dstats.iterrows():
        L.append(f"| {r['dataset']} | {int(r['n_samples'])} | {int(r['n_features'])} | "
                 f"{int(r['total_windows'])} | {int(r['n_regimes'])} | "
                 f"{int(r['n_transitions'])} | {int(r['n_recurrences'])} |")
    L.append("")

    L.append("## Primary results (mean over seeds)\n")
    L.append("| Dataset | Model | Macro-F1 | Accuracy | Precision | Recall | Adapt CPU (s) | Retrains | Reuses |")
    L.append("|---|---|---|---|---|---|---|---|---|")
    for n in ds:
        for _, r in prim[prim.dataset == n].iterrows():
            L.append(f"| {n} | {r['model']} | {r['macro_f1']:.4f} | {r['accuracy']:.4f} | "
                     f"{r['precision']:.4f} | {r['recall']:.4f} | {r['adapt_cpu_s']:.4f} | "
                     f"{int(r['retrains'])} | {int(r['reuses'])} |")
    L.append("")

    L.append("## CPU reduction vs Full Retraining\n")
    L.append("| Dataset | Model | Reduction % | 95% CI |")
    L.append("|---|---|---|---|")
    for _, r in cost.iterrows():
        L.append(f"| {r['dataset']} | {r['model']} | {r['reduction_pct']:.1f} | "
                 f"[{r['ci_low']:.1f}, {r['ci_high']:.1f}] |")
    L.append("")

    L.append("## Statistics\n")
    L.append("| Comparison | Dataset | dF1 (seed) | p_A | d_z | dF1 (win) | p_B |")
    L.append("|---|---|---|---|---|---|---|")
    for _, r in stats.iterrows():
        L.append(f"| {r['comparison']} | {r['dataset']} | {r['delta']:+.4f} | "
                 f"{r['p_seed']:.4f} | {r['d_z']:+.2f} | {r['delta_window']:+.4f} | "
                 f"{r['p_window']:.4f} |")
    L.append("")

    L.append("## Ablation\n")
    L.append("| Dataset | Config | Macro-F1 | Adapt CPU (s) | Retrains | Reuses | Refreshes |")
    L.append("|---|---|---|---|---|---|---|")
    for n in ds:
        for _, r in abl[abl.dataset == n].iterrows():
            L.append(f"| {n} | {r['model']} | {r['macro_f1']:.4f} | {r['adapt_cpu_s']:.4f} | "
                     f"{int(r['retrains'])} | {int(r['reuses'])} | {r['refreshes']:.1f} |")
    L.append("")

    L.append("## Detectors\n")
    L.append("| Dataset | Detector | Macro-F1 | Adapt CPU (s) | Retrains |")
    L.append("|---|---|---|---|---|")
    for n in ds:
        for _, r in det[det.dataset == n].iterrows():
            L.append(f"| {n} | {r['model']} | {r['macro_f1']:.4f} | {r['adapt_cpu_s']:.4f} | "
                     f"{int(r['retrains'])} |")
    L.append("")

    L.append("## Refit timing (isolation micro-benchmark)\n")
    L.append("| Trees | Buffer | Mean ms | Std ms |")
    L.append("|---|---|---|---|")
    for _, r in refit.iterrows():
        L.append(f"| {int(r['trees'])} | {int(r['buffer'])} | {r['mean_ms']:.1f} | "
                 f"{r['std_ms']:.1f} |")
    L.append("")

    with open(os.path.join(out, "FINAL_RESULTS.md"), "w") as f:
        f.write("\n".join(L) + "\n")
    print("FINAL_RESULTS.md written.")


if __name__ == "__main__":
    main()
